# Generated by Django 6.0.2 on 2026-03-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, default='Top-up', max_length=100),
        ),
    ]
